#!/usr/bin/env node
// postinstall.js — downloads the matching prebuilt binary from GitHub Releases.
//
// Invoked automatically by npm after `npm install -g @agent-sh/agent-workspace-linux`.
// If --ignore-scripts was used (e.g. pnpm default, some CI setups) this script
// will NOT run; the binary won't be present and the launcher will print a clear
// error at runtime. To recover, re-run installation with scripts enabled or
// invoke this file directly: `node node_modules/@agent-sh/agent-workspace-linux/scripts/postinstall.js`
//
// Release contract: every prebuilt binary asset must have a matching
// `<asset>.sha256` sidecar, generated by the GitHub release workflow. The
// installer verifies the sidecar before moving the binary into place.

"use strict";

const crypto = require("crypto");
const https = require("https");
const fs = require("fs");
const path = require("path");

// ── Platform / arch guard ────────────────────────────────────────────────────

if (process.platform !== "linux") {
  console.error(
    `agent-workspace-linux: unsupported platform "${process.platform}". ` +
      "This package only works on Linux."
  );
  process.exit(1);
}

const ARCH_MAP = {
  x64: "x86_64-unknown-linux-gnu",
  arm64: "aarch64-unknown-linux-gnu",
};

const rustTarget = ARCH_MAP[process.arch];
if (!rustTarget) {
  console.error(
    `agent-workspace-linux: unsupported CPU architecture "${process.arch}". ` +
      `Supported: ${Object.keys(ARCH_MAP).join(", ")}.`
  );
  process.exit(1);
}

// ── Paths ────────────────────────────────────────────────────────────────────

const pkg = require("../package.json");
const version = pkg.version; // e.g. "0.1.0"
const assetName = `agent-workspace-linux-${rustTarget}`;
const downloadUrl =
  `https://github.com/agent-sh/agent-workspace-linux/releases/download/` +
  `v${version}/${assetName}`;
const checksumUrl = `${downloadUrl}.sha256`;

const binDir = path.join(__dirname, "..", "bin");
const destPath = path.join(binDir, "agent-workspace-linux");
const tmpPath = destPath + ".tmp";
const tmpChecksumPath = tmpPath + ".sha256";

// ── Download helper (follows redirects, max 5 hops) ─────────────────────────

/**
 * Download `url` to `tmpFile`, following up to `maxRedirects` 3xx responses.
 * Resolves when the file is fully written, rejects on error or bad status.
 */
function download(url, tmpFile, maxRedirects = 5) {
  return new Promise((resolve, reject) => {
    function get(currentUrl, hopsLeft) {
      https
        .get(currentUrl, { headers: { "User-Agent": "node-fetch/postinstall" } }, (res) => {
          const { statusCode, headers } = res;

          // Follow redirects (GitHub releases always redirect to S3).
          if (statusCode >= 300 && statusCode < 400 && headers.location) {
            if (hopsLeft === 0) {
              res.resume();
              return reject(new Error(`Too many redirects downloading ${url}`));
            }
            res.resume(); // drain and ignore body
            return get(headers.location, hopsLeft - 1);
          }

          if (statusCode !== 200) {
            res.resume();
            return reject(
              new Error(
                `Failed to download ${url}: HTTP ${statusCode}. ` +
                  "Check that the release exists, includes the binary and .sha256 sidecar, " +
                  "and the version in package.json matches."
              )
            );
          }

          const out = fs.createWriteStream(tmpFile);
          res.pipe(out);
          out.on("finish", () => out.close(resolve));
          out.on("error", (err) => {
            fs.unlink(tmpFile, () => {}); // best-effort cleanup
            reject(err);
          });
          res.on("error", (err) => {
            fs.unlink(tmpFile, () => {});
            reject(err);
          });
        })
        .on("error", (err) => {
          fs.unlink(tmpFile, () => {});
          reject(err);
        });
    }

    get(url, maxRedirects);
  });
}

function removeFileQuietly(file) {
  try {
    fs.unlinkSync(file);
  } catch (_) {}
}

function parseSha256Sidecar(contents, expectedAssetName) {
  const lines = contents
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) {
    throw new Error("checksum sidecar is empty");
  }

  const candidates = [];
  for (const line of lines) {
    // Safe linear parse instead of potentially quadratic regex on untrusted sidecar content.
    // Sidecar format: "<64-hex> [ *]<filename>"
    const trimmed = line.trim();
    if (!/^[a-fA-F0-9]{64}(\s+\*?(\S.*)?)?$/.test(trimmed)) {
      throw new Error(`invalid checksum sidecar line: ${line}`);
    }
    const spaceIdx = trimmed.indexOf(' ');
    let checksum, fileNamePart;
    if (spaceIdx === -1) {
      checksum = trimmed;
      fileNamePart = null;
    } else {
      checksum = trimmed.slice(0, spaceIdx);
      fileNamePart = trimmed.slice(spaceIdx + 1).replace(/^\*?\s*/, '');
    }
    candidates.push({
      checksum: checksum.toLowerCase(),
      fileName: fileNamePart && fileNamePart.length ? fileNamePart.trim() : null,
    });
  }

  const namedMatch = candidates.find(
    ({ fileName }) => fileName && path.basename(fileName) === expectedAssetName
  );
  if (namedMatch) {
    return namedMatch.checksum;
  }

  throw new Error(
    `checksum sidecar does not contain an entry for ${expectedAssetName}`
  );
}

function fileSha256(file) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha256");
    const input = fs.createReadStream(file);

    input.on("error", reject);
    input.on("data", (chunk) => hash.update(chunk));
    input.on("end", () => resolve(hash.digest("hex")));
  });
}

async function verifyChecksum(binaryFile, sidecarFile, expectedAssetName) {
  const expected = parseSha256Sidecar(
    fs.readFileSync(sidecarFile, "utf8"),
    expectedAssetName
  );
  const actual = await fileSha256(binaryFile);

  if (actual !== expected) {
    throw new Error(
      `checksum mismatch for ${expectedAssetName}: expected ${expected}, got ${actual}`
    );
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  // Ensure bin/ directory exists (it should, tracked by git via .gitkeep, but
  // be defensive for edge-case installs).
  fs.mkdirSync(binDir, { recursive: true });

  // Remove stale tmp file from a previous interrupted install.
  removeFileQuietly(tmpPath);
  removeFileQuietly(tmpChecksumPath);

  console.log(
    `agent-workspace-linux: downloading ${assetName} v${version}…`
  );
  console.log(`  URL: ${downloadUrl}`);

  try {
    await download(downloadUrl, tmpPath);
  } catch (err) {
    // Clean up in case the file was partially created.
    removeFileQuietly(tmpPath);
    // The download error text embeds the request URL (built from
    // package.json's version + the target triple). Log a fixed message rather
    // than interpolating that value, to avoid a log-injection sink; the URL
    // itself is already printed above for debugging.
    console.error(
      "\nagent-workspace-linux: download failed. Verify the release exists " +
        "for your platform and that the version in package.json matches " +
        "(see the URL logged above)."
    );
    process.exit(1);
  }

  console.log(`agent-workspace-linux: downloading checksum for ${assetName}`);
  console.log(`  URL: ${checksumUrl}`);

  try {
    await download(checksumUrl, tmpChecksumPath);
    await verifyChecksum(tmpPath, tmpChecksumPath, assetName);
  } catch (err) {
    removeFileQuietly(tmpPath);
    removeFileQuietly(tmpChecksumPath);
    // Do not interpolate raw err.message (from untrusted sidecar/network) into logs.
    // This was flagged as log-injection (js/log-injection).
    console.error(
      "\nagent-workspace-linux: checksum verification failed. The sidecar may be malformed or the binary tampered."
    );
    process.exit(1);
  }
  removeFileQuietly(tmpChecksumPath);

  // Atomic rename: avoids leaving a half-written binary.
  try {
    fs.renameSync(tmpPath, destPath);
  } catch (err) {
    console.error(
      `agent-workspace-linux: could not move binary into place — ${err.message}`
    );
    process.exit(1);
  }

  // Mark executable.
  try {
    fs.chmodSync(destPath, 0o755);
  } catch (err) {
    console.error(
      `agent-workspace-linux: chmod failed — ${err.message}. ` +
        `Try: chmod 755 ${destPath}`
    );
    process.exit(1);
  }

  console.log(`agent-workspace-linux: binary installed at ${destPath}`);
}

if (require.main === module) {
  main().catch((err) => {
    console.error(`agent-workspace-linux: postinstall failed — ${err.message}`);
    process.exit(1);
  });
}

module.exports = {
  parseSha256Sidecar,
  fileSha256,
  verifyChecksum,
};
