#!/usr/bin/env node
// postinstall.js — downloads the matching prebuilt binary from GitHub Releases.
//
// Invoked automatically by npm after `npm install -g @agent-sh/agent-workspace-linux`.
// If --ignore-scripts was used (e.g. pnpm default, some CI setups) this script
// will NOT run; the binary won't be present and the launcher will print a clear
// error at runtime. To recover, re-run installation with scripts enabled or
// invoke this file directly: `node node_modules/@agent-sh/agent-workspace-linux/scripts/postinstall.js`
//
// Release contract: every prebuilt binary asset must have a matching
// `<asset>.sha256` sidecar, generated by the GitHub release workflow. The
// installer verifies the sidecar before moving the binary into place.

"use strict";

const crypto = require("crypto");
const https = require("https");
const fs = require("fs");
const path = require("path");

// ── Platform / arch guard ────────────────────────────────────────────────────

if (process.platform !== "linux") {
  console.error(
    `agent-workspace-linux: unsupported platform "${process.platform}". ` +
      "This package only works on Linux."
  );
  process.exit(1);
}

const ARCH_MAP = {
  x64: "x86_64-unknown-linux-gnu",
  arm64: "aarch64-unknown-linux-gnu",
};

const rustTarget = ARCH_MAP[process.arch];
if (!rustTarget) {
  console.error(
    `agent-workspace-linux: unsupported CPU architecture "${process.arch}". ` +
      `Supported: ${Object.keys(ARCH_MAP).join(", ")}.`
  );
  process.exit(1);
}

// ── Paths ────────────────────────────────────────────────────────────────────

const pkg = require("../package.json");
const version = pkg.version; // e.g. "0.1.0"
const assetName = `agent-workspace-linux-${rustTarget}`;
const downloadUrl =
  `https://github.com/agent-sh/agent-workspace-linux/releases/download/` +
  `v${version}/${assetName}`;
const checksumUrl = `${downloadUrl}.sha256`;

const binDir = path.join(__dirname, "..", "bin");
const destPath = path.join(binDir, "agent-workspace-linux");

// Concurrent installs share bin/, so staging must not use fixed file names: one
// install would delete or overwrite bytes another one is still verifying.
// mkdtemp allocates a unique directory atomically, inside bin/ so publishing
// stays a same-filesystem rename. Only the invocation that created a staging
// directory ever removes it — never another invocation's files. Catchable
// signals clean up before exit (below). A forced exit (SIGKILL/power loss)
// can still leave an abandoned directory, so the next install sweeps staging
// directories older than STALE_STAGING_MS; a live concurrent install is far
// younger than that (its download is bounded), so it is never touched.
let stagingDir = null;

function createStagingDir() {
  stagingDir = fs.mkdtempSync(path.join(binDir, ".staging-"));
  return stagingDir;
}

function cleanupStagingDir() {
  if (stagingDir === null) return;
  try {
    fs.rmSync(stagingDir, { recursive: true, force: true });
  } catch (_) {}
  stagingDir = null;
}

// Catchable termination (Ctrl-C, SIGTERM from a supervisor) must not leak the
// staging directory. Clean up, then re-raise with default disposition so the
// exit status still reflects the signal.
if (require.main === module && typeof process.on === "function") {
  for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {
    process.on(signal, () => {
      cleanupStagingDir();
      process.removeAllListeners(signal);
      process.kill(process.pid, signal);
    });
  }
}

// SIGKILL and power loss cannot be caught, so bound the leftovers: sweep
// staging directories that are clearly abandoned (older than STALE_STAGING_MS).
// Fresh ones may belong to a concurrent installer and are left alone.
const STALE_STAGING_MS = 60 * 60 * 1000;
function sweepStaleStagingDirs() {
  let entries;
  try {
    entries = fs.readdirSync(binDir, { withFileTypes: true });
  } catch (_) {
    return;
  }
  const now = Date.now();
  for (const entry of entries) {
    if (!entry.isDirectory() || !entry.name.startsWith(".staging-")) continue;
    const full = path.join(binDir, entry.name);
    try {
      if (now - fs.statSync(full).mtimeMs > STALE_STAGING_MS) {
        fs.rmSync(full, { recursive: true, force: true });
      }
    } catch (_) {}
  }
}

// ── Download helper (follows redirects, max 5 hops) ─────────────────────────

// Fail a download after a full minute without useful network progress. This
// catches missing headers and stalled response bodies without penalizing a slow
// connection that is still delivering bytes. Keep a separate generous ceiling
// so a pathological transfer cannot keep npm install alive forever.
const DOWNLOAD_IDLE_TIMEOUT_MS = 60 * 1000;
const DOWNLOAD_MAX_DURATION_MS = 30 * 60 * 1000;

/**
 * Download `url` to `tmpFile`, following up to `maxRedirects` 3xx responses.
 * Resolves when the file is fully written. Rejects on transport/status errors,
 * after DOWNLOAD_IDLE_TIMEOUT_MS without headers/body progress, or when the
 * generous DOWNLOAD_MAX_DURATION_MS hard ceiling is reached.
 */
function download(url, tmpFile, maxRedirects = 5) {
  return new Promise((resolve, reject) => {
    let settled = false;
    let out = null;
    let idleTimer = null;
    let maxDurationTimer = null;
    const requests = new Set();
    const responses = new Set();

    function settle(err) {
      if (settled) return;
      settled = true;
      clearTimeout(idleTimer);
      clearTimeout(maxDurationTimer);
      if (!err) return resolve();

      for (const req of requests) req.destroy();
      for (const res of responses) res.destroy();

      const removePartial = () => fs.unlink(tmpFile, () => reject(err));
      if (out && !out.closed) {
        out.once("close", removePartial);
        out.destroy();
      } else {
        removePartial();
      }
    }

    function resetIdleTimer() {
      if (settled) return;
      clearTimeout(idleTimer);
      idleTimer = setTimeout(
        () =>
          settle(
            new Error(
              `No download progress for ${DOWNLOAD_IDLE_TIMEOUT_MS} ms downloading ${url}`
            )
          ),
        DOWNLOAD_IDLE_TIMEOUT_MS
      );
    }

    function get(currentUrl, hopsLeft) {
      if (settled) return;
      try {
        const req = https.get(
          currentUrl,
          { headers: { "User-Agent": "node-fetch/postinstall" } },
          (res) => {
            responses.add(res);
            res.once("close", () => responses.delete(res));
            res.on("error", settle);
            if (settled) {
              res.destroy();
              return;
            }

            // Response headers are progress. A successful body must continue to
            // reset this timer whenever bytes arrive.
            resetIdleTimer();

            try {
              const { statusCode, headers } = res;

              if (statusCode >= 300 && statusCode < 400 && headers.location) {
                res.resume();
                if (hopsLeft === 0) {
                  settle(new Error(`Too many redirects downloading ${url}`));
                  return;
                }

                // Keep #98 intact: resolve relative redirects against the
                // current URL and never permit a downgrade away from HTTPS.
                let nextUrl;
                try {
                  nextUrl = new URL(headers.location, currentUrl);
                } catch (_) {
                  settle(new Error(`Invalid redirect location downloading ${url}`));
                  return;
                }
                if (nextUrl.protocol !== "https:") {
                  settle(new Error(`Refusing non-HTTPS redirect downloading ${url}`));
                  return;
                }
                get(nextUrl.href, hopsLeft - 1);
                return;
              }

              if (statusCode !== 200) {
                res.resume();
                settle(
                  new Error(
                    `Failed to download ${url}: HTTP ${statusCode}. ` +
                      "Check that the release exists, includes the binary and .sha256 sidecar, " +
                      "and the version in package.json matches."
                  )
                );
                return;
              }

              out = fs.createWriteStream(tmpFile);
              out.on("error", settle);
              out.on("finish", () => out.close((err) => settle(err || null)));
              res.on("data", resetIdleTimer);
              res.pipe(out);
            } catch (err) {
              settle(err);
            }
          }
        );
        requests.add(req);
        req.once("close", () => requests.delete(req));
        req.on("error", settle);
      } catch (err) {
        settle(err);
      }
    }

    maxDurationTimer = setTimeout(
      () =>
        settle(
          new Error(
            `Download exceeded ${DOWNLOAD_MAX_DURATION_MS} ms downloading ${url}`
          )
        ),
      DOWNLOAD_MAX_DURATION_MS
    );
    resetIdleTimer();
    get(url, maxRedirects);
  });
}

function parseSha256Sidecar(contents, expectedAssetName) {
  const lines = contents
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) {
    throw new Error("checksum sidecar is empty");
  }

  const candidates = [];
  for (const line of lines) {
    // Safe linear parse instead of potentially quadratic regex on untrusted sidecar content.
    // Sidecar format: "<64-hex> [ *]<filename>"
    const trimmed = line.trim();
    if (!/^[a-fA-F0-9]{64}(\s+\*?(\S.*)?)?$/.test(trimmed)) {
      throw new Error(`invalid checksum sidecar line: ${line}`);
    }
    // The line matched above, so the first 64 chars are the checksum; the rest
    // is "<whitespace>[*]<filename>". Scan forward (no regex backtracking) so
    // any whitespace delimiter works, not just a single space.
    const checksum = trimmed.slice(0, 64);
    let i = 64;
    while (i < trimmed.length && /\s/.test(trimmed[i])) i++;
    if (trimmed[i] === '*') i++; // sha256sum binary-mode marker
    while (i < trimmed.length && /\s/.test(trimmed[i])) i++;
    const fileNamePart = trimmed.slice(i);
    candidates.push({
      checksum: checksum.toLowerCase(),
      fileName: fileNamePart.length ? fileNamePart : null,
    });
  }

  const namedMatch = candidates.find(
    ({ fileName }) => fileName && path.basename(fileName) === expectedAssetName
  );
  if (namedMatch) {
    return namedMatch.checksum;
  }

  throw new Error(
    `checksum sidecar does not contain an entry for ${expectedAssetName}`
  );
}

function fileSha256(file) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha256");
    const input = fs.createReadStream(file);

    input.on("error", reject);
    input.on("data", (chunk) => hash.update(chunk));
    input.on("end", () => resolve(hash.digest("hex")));
  });
}

async function verifyChecksum(binaryFile, sidecarFile, expectedAssetName) {
  const expected = parseSha256Sidecar(
    fs.readFileSync(sidecarFile, "utf8"),
    expectedAssetName
  );
  const actual = await fileSha256(binaryFile);

  if (actual !== expected) {
    throw new Error(
      `checksum mismatch for ${expectedAssetName}: expected ${expected}, got ${actual}`
    );
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  // Ensure bin/ directory exists (it should, tracked by git via .gitkeep, but
  // be defensive for edge-case installs).
  fs.mkdirSync(binDir, { recursive: true });

  // Staging owned by this invocation only.
  sweepStaleStagingDirs();
  const stagingRoot = createStagingDir();
  const tmpPath = path.join(stagingRoot, assetName);
  const tmpChecksumPath = `${tmpPath}.sha256`;

  console.log(
    `agent-workspace-linux: downloading ${assetName} v${version}…`
  );
  console.log(`  URL: ${downloadUrl}`);

  try {
    await download(downloadUrl, tmpPath);
  } catch (err) {
    // Clean up in case the file was partially created.
    cleanupStagingDir();
    // The download error text embeds the request URL (built from
    // package.json's version + the target triple). Log a fixed message rather
    // than interpolating that value, to avoid a log-injection sink; the URL
    // itself is already printed above for debugging.
    console.error(
      "\nagent-workspace-linux: download failed. Verify the release exists " +
        "for your platform and that the version in package.json matches " +
        "(see the URL logged above)."
    );
    process.exit(1);
  }

  console.log(`agent-workspace-linux: downloading checksum for ${assetName}`);
  console.log(`  URL: ${checksumUrl}`);

  try {
    await download(checksumUrl, tmpChecksumPath);
    await verifyChecksum(tmpPath, tmpChecksumPath, assetName);
  } catch (err) {
    cleanupStagingDir();
    // Do not interpolate raw err.message (from untrusted sidecar/network) into logs.
    // This was flagged as log-injection (js/log-injection).
    console.error(
      "\nagent-workspace-linux: checksum verification failed. The sidecar may be malformed or the binary tampered."
    );
    process.exit(1);
  }

  // Mark the verified staging file executable *before* publishing it. Doing
  // this after the rename would expose a window where readers see a
  // non-executable binary at destPath, and a chmod failure there would already
  // have destroyed the previously installed, runnable binary.
  try {
    fs.chmodSync(tmpPath, 0o755);
  } catch (err) {
    cleanupStagingDir();
    console.error(
      `agent-workspace-linux: chmod failed — ${err.message}. ` +
        "The previously installed binary (if any) was left untouched; " +
        "re-run installation."
    );
    process.exit(1);
  }

  // Atomic rename: avoids leaving a half-written binary, and publishes a file
  // that is already executable.
  try {
    fs.renameSync(tmpPath, destPath);
  } catch (err) {
    cleanupStagingDir();
    console.error(
      `agent-workspace-linux: could not move binary into place — ${err.message}`
    );
    process.exit(1);
  }

  cleanupStagingDir();

  console.log(`agent-workspace-linux: binary installed at ${destPath}`);
}

if (require.main === module) {
  main().catch((err) => {
    // process.exit() is immediate, so staging must be removed before it: every
    // error path above cleans up synchronously, and this handles unexpected
    // throws in between.
    cleanupStagingDir();
    console.error(`agent-workspace-linux: postinstall failed — ${err.message}`);
    process.exit(1);
  });
}

module.exports = {
  sweepStaleStagingDirs,
  STALE_STAGING_MS,
  parseSha256Sidecar,
  fileSha256,
  verifyChecksum,
};
